# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=persevere_basic_gnn experiment=persevere/<PERSEVERE_EXPERIMENT>

defaults:
  - _persevere_optuna # inherit from base hparams PERSEVERE search config

hydra:
  sweeper:
    # define hyperparameter search space
    params:
      model.encoder.hidden_channels: choice(16, 32, 64)
      model.encoder.num_layers: range(2, 11)
      model.encoder.dropout: interval(0.0, 0.6) # uniform sampling between 0.0 and 0.6
      model.readout._target_: choice(torch_geometric.nn.SumAggregation, torch_geometric.nn.MeanAggregation, genesis.models.gnn.agg.LastAggregation)
      model.head.num_layers: range(1, 5)
      model.optimizer.weight_decay: tag(log, interval(1e-5,1e-3)) # log-uniform sampling between 1e-5 and 1e-3
