# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=persevere_gps+ga experiment=persevere/<PERSEVERE_GPS_GRAPH_ATTRS_EXPERIMENT>

defaults:
  - /hparams_search/persevere_gps # inherit from PERSEVERE search config for GPS
  - override /model: graph_level_gps+ga

hydra:
  sweeper:
    # Inherit from hyperparameter search space defined for GPS, and modify it to:
    # - add parameters specific to GPS with support for global features
    params:
      model.features_for_readout: choice(node, graph)
      # Add `LastAggregation` to extract CLS token in GPS+FTxA, which is appended to the end of global features tokens
      model.readout._target_: choice(torch_geometric.nn.SumAggregation, torch_geometric.nn.MeanAggregation, genesis.models.gnn.agg.LastAggregation)
