# Use `TabPFNRegressor` when task is regression, otherwise use `TabPFNClassifier`
_target_: ${op.ternary:${op:eq,${hparams.data.task},regression}, tabpfn.TabPFNRegressor, tabpfn.TabPFNClassifier}
random_state: ${seed} # Set the model's own random state for reproducibility
