# Updates the VN_G formulation of virtual nodes proposed in the paper:
# "Understanding Virtual Nodes: Oversquashing and Node Heterogeneity"
# https://arxiv.org/abs/2405.13526
# to explicit virtual node, and to support initializing it with graph-level features

defaults:
  - _vn_g_mixin

v2: true
graph_dim: ${oc.select:hparams.data.num_graph_features}
vn_g_kwargs:
  act: ${..act}
  dropout: ${..dropout}
