# GraphGPS configuration to use our proposed GAGPSConv extension to GPSConv layer, which adds support for Global Attributes.

defaults:
  - gps

graph_attr_embedding:
  _target_: torch.nn.Linear
  in_features: ${hparams.data.num_graph_features}
  out_features: ${..hidden_channels}
