# Use `XGBRegressor` when task is regression, otherwise use `XGBClassifier`
_target_: ${op.ternary:${op:eq,${hparams.data.task},regression}, xgboost.XGBRegressor, xgboost.XGBClassifier}
enable_categorical: true
random_state: ${seed}
# Manually configure objective, in case there isn't enough labels to infer number of classes and objective
# Note: `num_class` is not supported by XGBRegressor, and we benefit from Hydra dropping null config fields
num_class: ${oc.select:hparams.data.num_classes,null}
# if task is `regression` -> `reg:squarederror`
# if task is `multiclass` -> `multi:softmax`
# if task is `binary` -> `binary:logistic`
objective: ${cfg.xgboost_objective:${hparams.data.task}}
