# @package _global_

defaults:
  - paths: default
  - hydra: default
  - data/dataset@global_features: persevere_global_features
  - override data/dataset/imputer@global_features.imputer: iterative
  - _self_

source_dir: ${paths.data_dir}/PERSEVERE/graphs
pyg_raw_dir: ${paths.data_dir}/PERSEVERE/raw
node_link_data_nodes_key: nodes
node_link_data_edges_key: edges

attrs_to_aggregate: # aggregation function among max, min, mean and sum
  links:
    radius: [min, max, mean]
    transversal_obstruction: max

attrs_to_remove:
  nodes: [pos, radius]
  links: [
      id,
      name,
      lateral,
      lobe,
      lobes,
      centerline,
      radius, # since we extract the min, max, mean from the list
      min_radius, # since we recompute the aggregated radius attributes from the list of radii
      max_radius, # since we recompute the aggregated radius attributes from the list of radii
      mean_radius, # since we recompute the aggregated radius attributes from the list of radii
      contour_points,
      segments_below,
      total_vessel_voxels, # since ke keep the same information in volume (in cm3)
      total_vessel_volume_mm3, # since we keep the volume in cm3
      total_embolism_voxel_count, # since we keep the same information in volume (in cm3)
      total_embolism_volume_mm3, # since we keep the volume in cm3
      transversal_obstruction, # since we extract the max from the list
      has_embolism,
      # Remove fields for individual embolisms, since we keep the aggregated information only
      embolisms_ids,
      embolisms_voxel_counts,
      embolisms_volumes_mm3,
      embolisms_volumes_cm3,
    ]

global_features:
  target_attr: null # Disable the default target attribute, since we do not want to treat it differently at this stage
  drop_na: true # Do not silently propagate missing value NaNs

# disable output directory, since the script should be run interactively, and we don't need to save the output
hydra:
  output_subdir: null
  run:
    dir: .
