# @package _global_

defaults:
  - paths: default
  - hydra: default
  - data/dataset@clinical_data: persevere_clinical
  - override data/dataset/imputer@clinical_data.imputer: iterative
  - _self_

source_dir: ${paths.data_dir}/PERSEVERE/graphs
pyg_raw_dir: ${paths.data_dir}/PERSEVERE/raw
node_link_data_nodes_key: nodes
node_link_data_edges_key: edges

attrs_to_remove:
  nodes: [pos, radius]
  links:
    [
      id,
      name,
      lateral,
      lobe,
      centerline,
      radius,
      contour_points,
      ep_id,
      ep_coordinates,
      segments_below,
    ]

clinical_data:
  target_attr: null # Disable the default target attribute, since we do not want to treat it differently at this stage
  drop_na: true # Do not silently propagate missing value NaNs

# disable output directory, since the script should be run interactively, and we don't need to save the output
hydra:
  output_subdir: null
  run:
    dir: .
