# Use the base graph-level module to implement late fusion of graph-level features, with very slight changes:
# 1) Update the prediction head input channels to expect a concatenation of graph encoding and graph-level features,
# 2) Change the module class to `LateFusionGraphLevelLitModule`, which implements the concatenation of graph encoding
#    and graph-level features right before the prediction head
defaults:
  - graph_level

_target_: genesis.models.LateFusionGraphLevelLitModule

head:
  in_channels: ${op:add,${..encoder.hidden_channels},${..num_graph_features}}
