# Use the base graph-level module to implement late fusion of global features, with very slight changes:
# 1) Update the GNN input channels to expect a concatenation of graph encoding and global features.
defaults:
  - graph_level
  - override /data/dataset/transform@_global_.data.dataset.pre_transform: concat_global_features

encoder:
  # Add global graph features to compute the input dimension of the first GNN layer. The rest of the expression is
  # copied from the generic GNN config to account for positional encoding optionally concatenated to node features.
  in_channels: ${op:add, ${op:add,${hparams.data.num_node_features},${hparams.data.num_graph_features}}, ${op.ternary:${oc.select:hparams.data.pe_attr}, 0, ${oc.select:hparams.data.num_pe_features,0}} }
